name: Qrator
on:
  push:
    branches:
      - dev

jobs:
  sender:
    name: Move ticket to QA
    runs-on: ubuntu-latest

    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Find in commit messages
        id: find_jira_issue_id
        uses: atlassian/gajira-find-issue-key@master
        with:
          from: branch

      - name: Jira Issue Transition
        uses: atlassian/gajira-transition@v2.0.1
        with:
          issue: ${{ steps.find_jira_issue_id.outputs.issue }}
          transition: "QA"
