name: Qrator
on:
  pull_request:
    types: [opened, reopened]
  pull_request_review_comment:
    types: [created]

jobs:
  sender:
    name: sender
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: pull request send custom message with args
        uses: appleboy/telegram-action@master
        if: github.event_name == 'pull_request'
        with:
          to: ${{ secrets.tg_chat_id }}
          token: ${{ secrets.tg_token }}
          format: html
          args: |+
                ${{ github.actor }} відкрив PR <a href=\"${{ github.event.pull_request.html_url }}\">${{ github.event.pull_request.title }}</a>

      - name: pull request review comment send custom message with args
        uses: appleboy/telegram-action@master
        if: github.event_name == 'pull_request_review_comment'
        with:
          to: ${{ secrets.tg_chat_id }}
          token: ${{ secrets.tg_token }}
          format: html
          args: |+
                ${{ github.actor }} прокоментував <a href=\"${{ github.event.comment.html_url }}\">${{ github.event.pull_request.title }}</a>:
                <pre>${{ github.event.comment.body }}</pre>
